engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 80
  eslint:
    enabled: true
    config:
      config: ".eslintrc"
      extensions:
        - .js
        - .jsx
    checks:
      complexity:
        enabled: true
  csslint:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
    - "**.js"
    - "**.jsx"
    - "**.css"
    - "**.md"
