sudo: false
node_js:
  - 8
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn lint:md
  - yarn lint:js
  - yarn test
after_success:
  - codecov
notifications:
  email: false
