sudo: false
node_js:
  - 4
  - 5
  - 6
  - 7
  - 8
  - stable
  - iojs
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint:md
  - yarn lint:js
  - yarn test
after_success:
  - codecov
notifications:
  email: false
