sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 6
  - 8
  - stable
install:
  npm install --global codecov
before-script:
  - yarn
script:
  - yarn lint:md
  - yarn lint:js
  - yarn test
after_success:
  - codecov
