---
environement:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "7"
    - nodejs_version: "8"
cache:
  - "%LOCALAPPDATA%\\Yarn"
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

test_script:
  - node --version
  - yarn --version
  - yarn lint:md
  - yarn lint:js
  - yarn test

build: off
